### ISSUE TITLE
no charts visible if expected data file is not available

### ISSUE THREAD

**Issue by khassel** [sdetweil/MyCovid19#1]
Hi Sam,

thank you for this nice module!

As mentioned in discord I open this issue for further discussions here.

I think your commits of the last 2 days already solved the following problems:
- [x]  if data file for current day is not available, wait and retry
- [x]  if data file for current day is not available, use file of previous day until new file exists

Will wait for next data file tomorrow for testing ...

Further suggestions:
* the module needs some seconds to load, may we can get a `loading ...` message in the mirror
* same on errors, something like `ups, an error occured, you find more info's in the logs ...`

Thanks,

Karsten.

**Comment by sdetweil** [comment]
thank you for the issue and reporting the usability problems.

as you said, I think I have solved the refresh and display if no data when started (use previous day data)

will consider what I can do for the loading/errors.. error are logged to the console/pm2 logs file (depending on how you start mm)

**Comment by khassel** [comment]
> will consider what I can do for the loading/errors.. error are logged to the console/pm2 logs file (depending on how you start mm)

this is really "nice to have". I thought would be better to have any message on the screen so that users know something went wrong instead of having nothing on the screen ...

**Comment by sdetweil** [comment]
pull the latest, I have the 'loading' message ,

well, actually NOW.. had a readme conflict that I didn't notice... now resolved

**Comment by almostgithub** [comment]
> I think your commits of the last 2 days already solved the following problems:
> 
> * [x]   if data file for current day is not available, wait and retry
> * [x]   if data file for current day is not available, use file of previous day until new file exists
> 

Is there anyway to force this update of the chart? After a git pull update mine is stuck on loading data chart

**Comment by sdetweil** [comment]
@almostgithub  the data source is updated once a day.   the latest fix for the module will get the previous days data if the current is not yet available...    we are currently trying to load 2020/03/27
can u run with debug:true and  show me the console/pm2 logs
i see this on startup when todays data is not available..  yesterdays charts display
```
 getData  elapsed time since last updated=0 init=true
[07:45:50.511] [LOG]    fn=https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-27.xlsx
[07:45:50.540] [LOG]    Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
[07:45:50.545] [LOG]    getData  elapsed time since last updated=0 init=true
[07:45:50.545] [LOG]    fn=https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-27.xlsx
[07:45:51.181] [LOG]    processing response error=null response.code=404 file=rawdata-module_9_MyCovid19_3481_2020-03-27.xlsx
[07:45:51.181] [LOG]    no file, retry
[07:45:51.182] [LOG]    sending no data available notification
[07:45:51.185] [LOG]    getData  elapsed time since last updated=0 init=true
[07:45:51.185] [LOG]    fn=https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-26.xlsx
[07:45:51.187] [LOG]    processing response error=null response.code=404 file=rawdata-module_8_MyCovid19_7231_2020-03-27.xlsx
[07:45:51.187] [LOG]    no file, retry
[07:45:51.187] [LOG]    sending no data available notification
[07:45:51.189] [LOG]    getData  elapsed time since last updated=0 init=true
[07:45:51.189] [LOG]    fn=https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-26.xlsx
[07:45:51.939] [LOG]    processing response error=null response.code=200 file=rawdata-module_9_MyCovid19_3481_2020-03-26.xlsx
[07:45:51.940] [LOG]    have data
[07:45:52.984] [LOG]    sending data back to module=module_9_MyCovid19_3481
[07:45:52.990] [LOG]    processing response error=null response.code=200 file=rawdata-module_8_MyCovid19_7231_2020-03-26.xlsx
[07:45:52.990] [LOG]    have data
[07:45:53.738] [LOG]    sending data back to module=module_8_MyCovid19_7231

```

**Comment by khassel** [comment]
they have also csv format on their site which contains already todays data https://opendata.ecdc.europa.eu/covid19/casedistribution/csv 
maybe simpler to get because no date in the url

**Comment by sdetweil** [comment]
@khassel  no better, no worse..  if the data isn't there for today, I still have to retry..  now I know the data is missing, without downloading the file constantly and rereading it.. only to discover the data is not present..

**Comment by sdetweil** [comment]
looks like they might have deprecated the xlsx... so much fun...

**Comment by sdetweil** [comment]
@khassel @almostgithub   new version, now uses csv file..  same recovery process..

download file, check most recent date against today, display once, go into recovery, every 15 mins get file.... if dates match, display, then wait til tomorrow (saves data usage, be nice to upstream server, and network load)

oh, after git pull, u need to do another npm install as the data library changed

**Comment by sdetweil** [comment]
@khassel @almostgithub 

is the new update process working?   

they took a long time today to update the CSV file.. I had to email them

**Comment by almostgithub** [comment]
So i did a git pull in the MyCovid19 Folder, as well as an npm install in the MyCovid19 folder as well.. I just keep getting the undefined error. I copied as pasted your original sample config.js and put it in, still with the same results... 

Sorry if these are simple fixes, i'm somewhat new to coding. This is the only error in my dev console.


> Uncaught TypeError: Cannot read property 'debug' of undefined
    at Class.socketNotificationReceived (:8080/modules/MyCovi…9//MyCovid19.js:315)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (socket.io.js:6)
    at r.onevent (socket.io.js:8)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (socket.io.js:8)
    at r.<anonymous> (socket.io.js:8)
    at r.emit (socket.io.js:6)
    at r.ondecoded (socket.io.js:6)"

>

**Comment by khassel** [comment]
> is the new update process working?

yes, since 2 days (after change from xlsx to csv). Will now pull again ...

**Comment by khassel** [comment]
> Uncaught TypeError: Cannot read property 'debug' of undefined
> at Class.socketNotificationReceived (:8080/modules/MyCovi…9//MyCovid19.js:315)

looks like an error in your config, the following config works for my setup:

````
        {
                module:"MyCovid19",
                position:"bottom_left",
                config:{
                        countries:["Germany","Italy","Spain","France","USA","China"],
                        // line colors can be any definition of color either a name ,or a hex string
                        // one per country above, used in order,
                        line_colors:['red','white','green','yellow','blue','gray'],
                        //
                        chart_type:"cumulative_cases",  // or "cumulative deaths"
                        chart_title:"Cumulative Cases", // however u want to label
                        // the vertical steps on the chart.. how tall u want it to be and how mant increments
                        ranges:{min:0,max:8000,stepSize:10000},
                        // size of the chart in pixels
                        width: 600,
                        height: 500,
                        // only used if we need to debug something
                        debug:false,
                }
        },
````

**Comment by almostgithub** [comment]
That is what i thought as well. However i copied the sample one, as well as yours just now and still getting the same error.

Then on the MM is just displays loading data

**Comment by sdetweil** [comment]
i thought I was sending u both direct email..

do another git pull now

**Comment by almostgithub** [comment]
still having the same issue with the loading data on screen, and the only error i'm getting is the one posted before

**Comment by khassel** [comment]
can you post your config? Can try your config in my setup ...

**Comment by sdetweil** [comment]
so it looks like the git pull is not working

**Comment by sdetweil** [comment]
did u possibly edit the MyCovid19,js file? and the pull will not overlay it

**Comment by sdetweil** [comment]
@khassel  I don't think its a config problem.. I think he has a downlevel file/or 2.. there was a change day before yesterday which pushed the config info into the node_helper response.. which the modulename.js is trying to use..  but the line number doesn't match anything now..

**Comment by khassel** [comment]
your are right if he still has the same error in line 315 ...

**Comment by almostgithub** [comment]
Okay so i deleted the entire folder, re cloned the folder into my modules folder and did an npm install in the MyCovid19 folder and still getting the same error. Currently using the config that khassel posted 

> MyCovid19.js:312 Uncaught TypeError: Cannot read property 'debug' of undefined
    at Class.socketNotificationReceived (MyCovid19.js:312)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)

**Comment by sdetweil** [comment]
hm.. just did a new clone, new folder,  new npm install, 
same config, works as expected
my config 
```
{
			module:"MyCovid19",
			position:"top_left",
			config:{
				countries:["Italy","USA","China","Spain", "Germany"],
				// line colors can be any definition of color either a name ,or a hex string
				// one per country above, used in order,
				line_colors:['red','white','green','yellow','#34ebde','#34ebde'],
				//				
				chart_type:"deaths",  // or "cumulative deaths"
				chart_title:"new deaths", // however u want to label
				// the vertical steps on the chart.. how tall u want it to be and how mant increments 
				ranges:{min:0,max:1000,stepSize:100},
				// size of the chart in pixels
			    width: 400,
			    height: 400,	
			    // only used if we need to debug something
			    //debug:true,
			//    startDate:'02/01/2020',
			//    startLabel:['2/1/2020','3/1/2020']
			    //backgroundColor: 'white',
			}
		},	
```
nothing exciting

this machine has three charts displayed, al three came up no error


can u look in node_helper.js, this sends the data back to module
```
        if(payload.config.debug) console.log("sending data back to module="+payload.id)
       self.sendSocketNotification('Data', {id:payload.id, config:payload.config, data:results})
```

**Comment by sdetweil** [comment]
completed
