### ISSUE TITLE
Data not automatically updating

### ISSUE THREAD

**Issue by waldmeisterx** [sdetweil/MyCovid19#11]
Hi Sam,
installed the module with "git clone" and "npm install", applied my config an it displays the (two configued) graphs.
The only problem is, it doesn't update the data!?
Somewhere i read, it is updating only once a day, what would be ok. But it doesn't update.
Only at restart of mm it updates (downloads) the current data file.
Am I missing something?
Should it update at a specific time?
Or does it check or a new data file and updates then?
If one could help, this would be fine.

This is one of my two configs:
`{
	module: "MyCovid19",
	position: "bottom_left",
	config: {
		countries: ['Germany','Austria'],
		line_colors: ['red','green','yellow','blue','orange','pink','white',],
		chart_type: "cases",  // or "deaths"
		chart_title: "Fälle/Tag", // however u want to label
		startDate: '03/01/2020',
		ranges:{min:0,max:40000,stepSize:10000},
		xAxisLabel: 'Datum',
		yAxisLabel: 'Infektionen',
		width: 500,
		height: 350,
		debug: false,
	}
},`

Regards
Dirk

**Comment by sdetweil** [comment]
should update daily, the time depends on when they publish refreshed data..   I start checking at 6am, every 15 mins.. 

some change might be small.. u can hover over a line and see the dates.. 

if still stuck, add debug:true, to the chart and then 
npm start >somefile

the traces will be in somefile,
attach here or send to me, same userid at gmail

**Comment by waldmeisterx** [comment]
Sorry for the delay. I haven't solved it yet, but I'm not sure, if the mirror has a wifi problem. Maybe there is no connection, if it should pull new data. Have to add a new wifi usb module and test with it again.

**Comment by waldmeisterx** [comment]
traces sent by mail to you

**Comment by sdetweil** [comment]
got them

**Comment by waldmeisterx** [comment]
so while no solution until now, my current workaround is to restart mm every night via cron

**Comment by sdetweil** [comment]
i pushed a change a few weeks ago.., did u do a git pull?

may have to turn on debug, 
add 
debug: true,  

to the module config block

**Comment by waldmeisterx** [comment]
yes i updated the module quite after your update, have to try debug again...

**Comment by sdetweil** [comment]
is this still failing?

**Comment by humdinger44** [comment]
Wow, you were out for a while. Glad to hear you are recovering.


I started tracking my state's covid data somewhere else to make room for
another module so I haven't been keeping any eye on this functionality

**Comment by waldmeisterx** [comment]
@sdetweil no, it was running until 22.4.2021

Then i got this error [MM crashing (after pi os update?)](https://forum.magicmirror.builders/topic/14976/mm-crashing-after-pi-os-update/14) where we had contact. I disabled the module since i get these new errors.
I'd close this one too, because of the new problem.

**Comment by sdetweil** [comment]
@humdinger44 thanks.. been home a couple months now, and slowly getting back into the flow..

**Comment by sdetweil** [comment]
@waldmeisterx  ok, I sent another email , I will close this.
