### ISSUE TITLE
Cannot find module 'csvtojson'

### ISSUE THREAD

**Issue by mitch1138** [sdetweil/MyCovid19#12]
Really looking forward to this.  After installation, I receive the following error on starting MM: 

[2020-11-17 16:12:58.649] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'csvtojson'
Require stack:
- /home/pi/MagicMirror/modules/MyCovid19/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js

Any suggestions to address?  Many Thanks, Dave

**Comment by sdetweil** [comment]
did u do the required 
npm install 
in the module folder

doc 
chartjs, loaded via npm install

**Comment by mitch1138** [comment]
I installed in the wrong module.  Works fine, many thanks.
