### ISSUE TITLE
Add charts rotation

### ISSUE THREAD

**Issue by fireport** [sdetweil/MyCovid19#2]
I like your module but, unfortunately, it isn't possible to display tho chart type at once for the same nation.
Please, can you add graphs rotation?

**Comment by sdetweil** [comment]
sorry, don't understand there are 4 separate charts.. each one is displayed separately, in a different area

**Comment by fireport** [comment]
This is the problem. My magic mirror is very crowded and for me should be
better if the  charts should rotate in the same region.

Il ven 27 mar 2020, 20:46 sam detweiler <notifications@github.com> ha
scritto:

**Comment by sdetweil** [comment]
ok, understand now, thx.. it would take a significant redesign to make them rotate. sorry.

**Comment by Plainbroke** [comment]
I need to make the fonts bigger what did you use for sizing   ie xsmall, small, medium, large, xlarge, big?
so i can fix in custom.css
Appreciate the help...

**Comment by sdetweil** [comment]
@Plainbroke I will have to expose the font name and size.   It is hidden inside the charting library

**Comment by Plainbroke** [comment]
Thank you for the info I will wait for the update.

Jeff Burdick

**Comment by sdetweil** [comment]
@Plainbroke 

I have uploaded a new version which exposes all the font capabilities for all the text..  see the readme.. its quite a lot of settings

a default and individual control for each part (title, legend, x and y axes labels and ticks)

I don't know what the default fontFamily is. the font size is dynamic based on the chart size,
also control of bold/italic... 'style' settings

the doc for chartjs says this about the defaults, I don't know how u have 3 default fontFamily's
https://www.chartjs.org/docs/latest/general/fonts.html
|field|type|default| description  
-- | -- | -- | --
defaultFontColor | Color | '#666' | Default font color for all text.
defaultFontFamily | string | "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif" | Default font family for all text.
defaultFontSize | number | 12 | Default font size (in px) for text. Does not apply to radialLinear scale point labels.
defaultFontStyle | string | 'normal' | Default font style. Does not apply to tooltip title or footer. Does not apply to chart title.

**Comment by sdetweil** [comment]
close this one, new comments on colors in issue #3

**Comment by Mahieedaboss** [comment]
Could try

https://github.com/barnabycolby/MMM-Carousel

I found that slides was helpful
