### ISSUE TITLE
After last update graphs dont popup

### ISSUE THREAD

**Issue by fireport** [sdetweil/MyCovid19#8]
After last upgrade, graphs don't popup anyore.
The assigned region remain blask.
At startup the message related to update data appears in the rigth posistion.
This is my config.js

 `{
            module: "MyCovid19",
            position: "bottom_center",
            config: {
                countries: ["Italy"],
                // line colors can be any definition of color either a name ,or a hex string
                // one per country above, used in order,
                line_colors: ['red'],
                //
                chart_type: "deaths", // or "cumulative deaths"
                chart_title: "Morti al giorno per Covid-19", // however u want to label
                // the vertical steps on the chart.. how tall u want it to be and how mant increments
                ranges: {
                    min: 0,
                    max: 1000,
                    stepSize: 100
                },
                // size of the chart in pixels
                width: 320,
                height: 400,
                startDate: "03/01/2020",
                // only used if we need to debug something
                debug: true,
            }
        }, `

Software is running on a raspberry PI 3 b+

**Comment by humdinger44** [comment]
Same. I saw a msg there was an npm update so I ran that and it hasn't worked since.

**Comment by sdetweil** [comment]
npm update???   u mean npm install?

**Comment by humdinger44** [comment]
When I got the msg for the last update I ran it using git pull. Then Iv been in the habit of running npm install so I did that. When that completed there was a msg saying I should run "npm install -g npm" so I did. After that, rebooted, no graphs. Ran git pull and npm install again, reboot, still nothing.

**Comment by sdetweil** [comment]
>msg there was an npm update

oh THAT.. NEVER EVER do that..  leaves everything a mess..

NOW u have to go redo the MagicMirror npm install cause the npm version changed
erase the node_modules folder and the package-lock.json file where u find them (base any any module) and then run npm install in base folder and all module folders where there is a package.json file. 

oops, I see my module problem, do another git pull  please..

thanks for the report

**Comment by humdinger44** [comment]
Graphs are back! Thanks for your support.
